### ISSUE TITLE
Channel volume

### ISSUE THREAD

**Issue by pinobatch** [NovaSquirrel/ft2pently#13]
Four commands were added to Pently in [commit 64fc37d](https://github.com/Qix-/pently/commit/64fc37dec66c592d14e56190529ee46e800c968f), changing the channel volume. From quiet to loud, these are `pp`, `mp`, `mf`, and `ff`.  How hard would it be to map FamiTracker's volume column to these?
* <6: `pp`
* 6-9: `mp`
* A-C: `mf`
* D-F: `ff`

**Comment by NovaSquirrel** [comment]
Not very hard, it turns out. Implemented, should work.
