### ISSUE TITLE
Sxx effect produces wrong rhythm and missing notes

### ISSUE THREAD

**Issue by pinobatch** [NovaSquirrel/ft2pently#14]
This FTM uses S00 as an alternate note cut and S04 as staccato. When I convert it, the note on the row below the S04 disappears, and the rhythm is wrong (extra delay).

I've attached the FTM and a Pently score containing the converter output followed by a handcoded song showing correct behavior.
[Sxx_test.zip](https://github.com/NovaSquirrel/ft2pently/files/1046259/Sxx_test.zip)

**Comment by NovaSquirrel** [comment]
Fixed, I think
