### ISSUE TITLE
Release a Windows executable

### ISSUE THREAD

**Issue by pinobatch** [NovaSquirrel/ft2pently#22]
The composer for my next video game project wants to preview conversion from FamiTracker. I might be able to walk him through the [instructions](https://github.com/pinobatch/nrom-template) to set up Python, Pillow, ca65, and MSYS, but not necessarily MinGW. So please provide a Windows executable through [releases](https://help.github.com/articles/creating-releases/).

**Comment by NovaSquirrel** [comment]
Sure, I'll make a release.
