### ISSUE TITLE
Don't rely on comments when parsing text export

### ISSUE THREAD

**Issue by pinobatch** [NovaSquirrel/ft2pently#36]
I saw this twice in ft2p.c
```c
    // export things if needed
    if(!strcmp(buffer, "# End of export")) {
```
Lines beginning with `# ` are comments. Comments are not guaranteed to appear in files exported from future versions of FamiTracker or in files exported by other tools whose output FamiTracker can import. It'd be better to perform these actions upon reaching the end of the file.

**Comment by NovaSquirrel** [comment]
I already refactored the code to look for the actual end of the file, rather than this comment, so I'm closing this
